name: WordPress CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0

    - name: Install dependencies
      run: composer install

    - name: Lint
      run: vendor/bin/phpcs --standard=WordPress wp-content/

    - name: Run tests
      run: vendor/bin/phpunit

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t myusername/wordpress-site:${{ github.sha }} .

    - name: Push Docker image
      run: docker push myusername/wordpress-site:${{ github.sha }}
